### ISSUE TITLE
登录AppStore想要下载的时候提示被停用了

### ISSUE THREAD

**Issue by daiyangyang945** [v2ss/shadowrocket#22]
![IMG_5799](https://user-images.githubusercontent.com/26043410/75338914-7d79e500-58ca-11ea-9ca5-9518491df131.PNG)

**Comment by v2ss** [comment]
亲 使用的那个appID？

daiyangyang945 <notifications@github.com>于2020年2月26日 周三下午7:03写道：

**Comment by daiyangyang945** [comment]
xb2a1303@icloud.com

**Comment by v2ss** [comment]
fix

**Comment by 495495** [comment]
> xb2a1303@icloud.com

请问下密码多少？我被锁了 不记得密码了 谢谢
