### ISSUE TITLE
Version: 2.1.48 在ios 13.3.1上安装后，打开app，屏幕显示火箭图案后闪退。

### ISSUE THREAD

**Issue by chxb** [v2ss/shadowrocket#25]
Version: 2.1.48 在ios 13.3.1上安装后，打开app，屏幕显示火箭图案后闪退。

**Comment by stephvino** [comment]
同闪退。。

**Comment by v2ss** [comment]
提问前，先搜索问题，您碰到的别人都碰到了哈！问题都置顶了还看不到吗？ 
推荐阅读。《提问的智慧》
