### ISSUE TITLE
不能使用在线安装

### ISSUE THREAD

**Issue by jdleung** [v2ss/shadowrocket#28]
没有vpn才需要安装小火箭，但在线安装的链接却需要vpn才能登录。可以放一个可以国内访问的网址吗？谢谢

**Comment by v2ss** [comment]
https://lueying.online 购买就可以了！
能打开github,就可以离线安装哈

**Comment by jdleung** [comment]
> https://lueying.online 购买就可以了！
> 能打开github,就可以离线安装哈

github.com能上，但在线安装的github.io就不行了。购买的可以使用Trojan吗？
