### ISSUE TITLE
关于AppId提示锁定，无法登录问题

### ISSUE THREAD

**Issue by v2ss** [v2ss/shadowrocket#33]
AppId 异地登录造成锁定的问题，
因人力有限，每天固定时间解锁！
在此期间，接受邮件解锁

- 13:10-13:20 
- 22:10-22:30

**Comment by 495495** [comment]
请问下xb2a1303@icloud.com的密码是多少 谢谢啦

**Comment by chuhaibo** [comment]
发到哪个邮箱？需要提供什么信息？

**Comment by v2ss** [comment]
> 请问下[xb2a1303@icloud.com](mailto:xb2a1303@icloud.com)的密码是多少 谢谢啦
ssts.meA1
