### ISSUE TITLE
在ios 系统13.3 点击app就崩溃

### ISSUE THREAD

**Issue by yangjie5250** [v2ss/shadowrocket#7]

**Comment by v2ss** [comment]
请找到页面彩蛋、使用appID 到 app store里面下载即可

yangjie5250 <notifications@github.com>于2019年12月31日 周二下午5:07写道：

**Comment by yangjie5250** [comment]
thanks！

**Comment by rzhangpku** [comment]
这个Apple id是需要美国地区的Apple id吗，谢谢！

**Comment by v2ss** [comment]
如果闪退，是因为ios的系统问题！使用下载页面上新的appID 登录app store 下载即可！

Rong Zhang <notifications@github.com>于2020年1月11日 周六下午12:03写道：

**Comment by LiChaY** [comment]
锁定了，需要解锁thank you

**Comment by reY2ox** [comment]
我也是，目前账号锁定了。
